name:                regex-hs
version:             0.1.0.0
github:              "github.com/elliotheisler"
license:             BSD3
author:              "Elliot Heisler"
maintainer:          "elliotheisler9@gmail.com"
copyright:           "2022 Elliot Heisler"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/regex-hs#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- QuickCheck
- hspec

library:
  source-dirs: src

executables:
  regex-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - regex-hs

tests:
  regex-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - regex-hs
